/* Empty mdss_pll trace header to bypass compilation errors */
/* This file is normally auto-generated by the kernel tracing system */

#ifndef _TRACE_EVENTS_MDSS_PLL_H
#define _TRACE_EVENTS_MDSS_PLL_H

#endif /* _TRACE_EVENTS_MDSS_PLL_H */
