#!/bin/bash

# 修复MDSS PLL编译错误
# 创建空的trace事件头文件来绕过编译错误

set -e

# 从参数或环境变量获取内核目录
KERNEL_DIR="${1:-$(pwd)}"

echo "=========================================="
echo "修复MDSS PLL编译错误"
echo "=========================================="
echo ""
echo "内核目录: $KERNEL_DIR"
echo ""

# 创建trace/events目录
mkdir -p "$KERNEL_DIR/include/trace/events"

# 创建空的mdss_pll.h文件
echo "创建空的mdss_pll.h文件..."
cat > "$KERNEL_DIR/include/trace/events/mdss_pll.h" << 'EOF'
/* Empty mdss_pll trace header to bypass compilation errors */
/* This file is normally auto-generated by the kernel tracing system */

#ifndef _TRACE_EVENTS_MDSS_PLL_H
#define _TRACE_EVENTS_MDSS_PLL_H

#endif /* _TRACE_EVENTS_MDSS_PLL_H */
EOF

# 禁用CREATE_TRACE_POINTS以避免编译错误
echo "禁用CREATE_TRACE_POINTS..."

# 修复MDSS DSI PLL文件
if [ -f "$KERNEL_DIR/drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c" ]; then
    echo "修复mdss-dsi-pll-10nm.c..."
    sed -i 's/#define CREATE_TRACE_POINTS/\/\/#define CREATE_TRACE_POINTS/g' "$KERNEL_DIR/drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c"
fi

# 修复MDSS DP PLL文件
if [ -f "$KERNEL_DIR/drivers/clk/qcom/mdss/mdss-dp-pll-10nm.c" ]; then
    echo "修复mdss-dp-pll-10nm.c..."
    sed -i 's/#define CREATE_TRACE_POINTS/\/\/#define CREATE_TRACE_POINTS/g' "$KERNEL_DIR/drivers/clk/qcom/mdss/mdss-dp-pll-10nm.c"
fi

echo ""
echo "=========================================="
echo "MDSS PLL编译错误修复完成！"
echo "=========================================="
echo ""
echo ""
echo "=========================================="
echo "MDSS PLL编译错误修复完成！"
echo "=========================================="
echo ""
echo "已创建空的mdss_pll.h文件"
echo "已注释掉CREATE_TRACE_POINTS定义"
echo ""
echo "这样可以绕过trace事件系统的编译依赖"