#!/bin/bash

# 修复MDSS PLL编译错误
# 创建空的trace事件头文件来绕过编译错误

set -e

echo "=========================================="
echo "修复MDSS PLL编译错误"
echo "=========================================="
echo ""

# 创建trace/events目录
mkdir -p include/trace/events

# 创建空的mdss_pll.h文件
echo "创建空的mdss_pll.h文件..."
cat > include/trace/events/mdss_pll.h << 'EOF'
/* Empty mdss_pll trace header to bypass compilation errors */
/* This file is normally auto-generated by the kernel tracing system */

#ifndef _TRACE_EVENTS_MDSS_PLL_H
#define _TRACE_EVENTS_MDSS_PLL_H

#endif /* _TRACE_EVENTS_MDSS_PLL_H */
EOF

echo "空的mdss_pll.h文件已创建"
echo ""

# 另一种方法：注释掉CREATE_TRACE_POINTS行
echo "注释掉CREATE_TRACE_POINTS行..."
if [ -f "drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c" ]; then
 sed -i 's/#define CREATE_TRACE_POINTS/\/\/#define CREATE_TRACE_POINTS/g' drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c
 echo "已注释掉drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c中的CREATE_TRACE_POINTS"
fi

if [ -f "drivers/clk/qcom/mdss/mdss-dp-pll-10nm.c" ]; then
 sed -i 's/#define CREATE_TRACE_POINTS/\/\/#define CREATE_TRACE_POINTS/g' drivers/clk/qcom/mdss/mdss-dp-pll-10nm.c
 echo "已注释掉drivers/clk/qcom/mdss/mdss-dp-pll-10nm.c中的CREATE_TRACE_POINTS"
fi

if [ -f "drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c" ]; then
 sed -i 's/#define CREATE_TRACE_POINTS/\/\/#define CREATE_TRACE_POINTS/g' drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c
 echo "已注释掉drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c中的CREATE_TRACE_POINTS"
fi

echo ""
echo "=========================================="
echo "MDSS PLL编译错误修复完成！"
echo "=========================================="
echo ""
echo "已创建空的mdss_pll.h文件"
echo "已注释掉CREATE_TRACE_POINTS定义"
echo ""
echo "这样可以绕过trace事件系统的编译依赖"